name: covariance
channels:
  - conda-forge
dependencies:
  - ipython
  - pytest
  - pytest-cov
  - codecov
  - coverage
  - coveralls
  - pylint
  - black
  - numpy
  - sympy
  - uncertainties
  - pint
  - unyt
  - wrapt
  - python-box
  - clifford
  - pip:
    - galgebra
